routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@wellcome')->name('default');
//Route::get('/Dashboard','UserController@dashboard')->name('userDashboard');
Route::get('/Dashboard','HomeController@index')->name('dashboard');
Route::get('/order','OrderController@index')->name('orderD');
Route::get('/profile','UserController@userprofile')->name('profile');
Route::get('/changepassword','UserController@changepassword')->name('changepassword');
Route::post('/updateProfile/{id}','UserController@updateProfile')->name('Updateprofile');
Route::post('/updatePassword/{id}','UserController@updatePassword')->name('updatePassword');
Route::resource('users', 'UserController');
Route::resource('countries', 'CountryController');
Route::resource('hotels', 'HotelController');
Route::resource('photos', 'PhotoController');
Route::resource('airports', 'AirPortController');
Route::resource('advertisments', 'AdvertismentController');
Route::resource('pages', 'PageController');
Route::get('/getPackage/{id}', 'PageController@getPackage')->name('getPackage');
Route::resource('packages', 'PackageController');
Route::resource('orders', 'OrderController');
Route::get('ajax/user','UserController@ajax')->name('ajaxUser');
Route::get('ajax/country','CountryController@ajax')->name('ajaxCountry');
Route::get('ajax/hotel','HotelController@ajax')->name('ajaxHotel');
Route::get('ajax/airport','AirPortController@ajax')->name('ajaxAirport');
Route::get('ajax/advertisement','AdvertismentController@ajax')->name('ajaxAdvertisement');
Route::get('ajax/pages','PageController@ajax')->name('ajaxPage');
Route::get('ajax/package','PackageController@ajax')->name('ajaxPackage');
Route::get('ajax/order','OrderController@ajax')->name('orderAjax');
Auth::routes();
Route::get('/registeragency','PageController@agency')->name('regAgecny');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/activate/token={token}', 'ActivationController@activate')->name('activate');

resources/views/activate.blade.php
@extends('master')
@section('content')
    <div class="jumbotron text-center">
        <h1 class="display-3">Thank You!</h1>
        <p class="lead"><strong>Your Email is verified</strong></p>
        <hr>
{{--        <p class="lead">--}}
{{--            <a class="btn btn-primary btn-sm" href="https://bootstrapcreative.com/" role="button">Continue to homepage</a>--}}
{{--        </p>--}}
    </div>
@endsection

resources/views/changepass.blade.php
@extends('master')
@section('content')
    <!--DASHBOARD-->
    <section>
        <div class="db">
            <!--LEFT SECTION-->
            @include('leftbar')
            <!--CENTER SECTION-->
            <div class="db-2">
                <div class="tr-regi-form" style="width:80%;">
                    <h4>Change Password</h4>

                    <form action="{{route('updatePassword',$user->id)}}" method="post" class="col s12">
                        @csrf
                        <div class="row">
                            <div class="input-field col s12">
                                <h5 style="text-align:left">New Password</h5>
                                <input type="password" name="password" class="validate">
                            </div>
                        </div>


                        <div class="row">

                            <div class="input-field col s12">
                                <h5 style="text-align:left">Confirm Password</h5>
                                <input type="password" name="confirm_password" class="validate">
                            </div>

                            <div class="row">
                                <div class="input-field col s12">
                                    <input type="submit" value="Submit"
                                           class="waves-effect waves-light btn-large full-btn"></div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </section>
    <!--END DASHBOARD-->
@endsection

resources/views/headerSearch.blade.php
<!--HEADER SECTION-->

<section>
    <div class="v2-hom-search">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-md-4">
                    <!-- <div class="v2-ho-se-ri">

                        <h1>Gateway to the Holy Places</h1>
                        <p>Find Hajj and Umrah Packages</p>

                    </div>	 -->
                </div>
                <div class="col-xs-12 col-md-12 col-md-8 main-body">
                    <div class="" style="padding: 20px; width: 100%; float: left;  background: rgba(0, 0, 0, 0.85); box-shadow: inset 0 1px 0 rgba(255,255,255,.15), 0 1px 2px rgba(0,0,0,.05); border: 1px solid #161616; color: #fff">
                        <h1 style="color: goldenrod;  font-family: 'Open Sans Condensed', sans-serif; font-weight: 700;">Gateway to the Holy Places</h1>
                        <p style="margin-bottom: 15px; font-size: 21px; font-weight: 200;color: #7eb216;">Find Hajj and Umrah Packages</p>

                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-7 show">
                                <ul class="nav nav-tabs hajjUmrahNav" role="tablist">
                                    <li class="nav-item active">
                                        <a class="nav-link active" data-toggle="tab" href="#home" >Hajj</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#menu1">Umrah</a>
                                    </li>
                                </ul>
                                <!-- Tab panes -->
                                <div class="tab-content" style="text-align: justify;">
                                    <div id="home" class="container tab-pane active"><br>
                                        <form>
                                            <div class="checkbox">
                                                <input class="checkbox" type="checkbox" required value="">
                                                <label style="font-size: 1em;color: #ffffff;">Makkah First</label>
                                            </div>
                                            <div class="checkbox">
                                                <input type="checkbox" value="">
                                                <label style="font-size: 1em;color: #ffffff;">Madina First</label>
                                            </div>
                                            <div class="checkbox">
                                                <input type="checkbox" value="">
                                                <label style="font-size: 1em;color: #ffffff;">By Price</label>
                                            </div>
                                            <div class="checkbox">
                                                <input type="checkbox" value="">
                                                <label style="font-size: 1em;color: #ffffff;">By Dates</label>
                                            </div>
                                            <div class="checkbox">
                                                <input type="checkbox" value="">
                                                <label style="font-size: 1em;color: #ffffff;">Hotels Stars (Ratings)</label>
                                            </div>
                                            <div class="checkbox">
                                                <input type="checkbox" value="">
                                                <label style="font-size: 1em;color: #ffffff;">See All</label>
                                            </div>
                                            <div style="border-bottom: .5px solid #fff; width: 20%; margin-top: 5px"></div>
                                        </form>

                                        <form>
                                            <p>Additional Keywords</p>
                                            <div class="row">
                                                <div class="col-xs-12 col-sm-8 col-md-8 col-lg-3 col-xl-3" style="padding: 0px !important;">
                                                    <input type="text" name="Keywords" placeholder="Keywords" class="form-control" style="width: 100%">
                                                </div>
                                            </div>
                                            <br>
                                            <button class="btn btn-primary search-button">Search</button>
                                            <button class="btn btn-info">Clear Search</button>
                                        </form>
                                        <br>
                                        <a href="Advanced.html" style="color: goldenrod; font-size: 1.4rem; display: block;float: left;">Advanced Search</a>
                                    </div>
                                    <div id="menu1" class="container tab-pane fade"><br>
                                        <form>
                                            <div class="checkbox">
                                                <label style="font-size: 1em;color: #ffffff;"><input type="checkbox" value="">Makkah First</label>
                                            </div>
                                            <div class="checkbox">
                                                <label style="font-size: 1em;color: #ffffff;"><input type="checkbox" value="">Madina First</label>
                                            </div>
                                            <div class="checkbox">
                                                <label style="font-size: 1em;color: #ffffff;"><input type="checkbox" value="">By Price</label>
                                            </div>
                                            <div class="checkbox">
                                                <label style="font-size: 1em;color: #ffffff;"><input type="checkbox" value="">By Dates</label>
                                            </div>
                                            <div class="checkbox">
                                                <label style="font-size: 1em;color: #ffffff;"><input type="checkbox" value="">Hotels Stars (Ratings)</label>
                                            </div>
                                            <div class="checkbox">
                                                <label style="font-size: 1em;color: #ffffff;"><input type="checkbox" value="">See All</label>
                                            </div>
                                            <div style="border-bottom: .5px solid #fff; width: 20%; margin-top: 5px"></div>
                                        </form>

                                        <form>
                                            <p>Additional Keywords</p>
                                            <div class="row">
                                                <div class="col-xs-12 col-sm-8 col-md-8 col-lg-3 col-xl-3">
                                                    <input type="text" name="Keywords" placeholder="Keywords" class="form-control" style="width: 100%">
                                                </div>
                                            </div>
                                            <br>
                                            <button class="btn btn-primary">Search</button>
                                            <button class="btn btn-info">Clear Search</button>
                                        </form>
                                        <br>
                                        <a href="#" style="color: goldenrod; font-size: 1.4rem; display: block;float: left;">Advanced Search</a>

                                        <br><br>
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <p style="position: relative; bottom: -13px; left: 56px;">By using Urood.com you hereby agree to the <a href="#" style="color: goldenrod; font-size: 1.4rem;" >Terms and Conditions</a> of the website.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-4 col-sm-4 col-md-5 browserr tablet" style="color: #7eb216;">
                                <span>Total 0 Packages Found</span>
                                <a href="#" style="background: #0a8c8c; background: linear-gradient(to bottom,#0a8c8c,#26a69a); color: #fff; padding: 7px 12px; line-height: 30px; font-size: 12px;" style="display: inline-block;width: 100%;max-width: 100%;min-width: 100% !important;">Browse All</a>
                            </div>
                            <br><br>
                            <div class="row">
                                <div class="col-xs-12">
                                    <p style="margin-top: 10px">By using Urood.com you hereby agree to the <a href="#" style="color: goldenrod; font-size: 1.4rem;" >Terms and Conditions</a> of the website.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--END HEADER SECTION-->

resources/views/home.blade.php
@extends('master')
@section('content')
    <!--DASHBOARD-->
    <section>
        <div class="db">
            <!--LEFT SECTION-->
        @include('leftbar')
        <!--CENTER SECTION-->
            <div class="db-2">
                <div class="db-2-com db-2-main">

                    <div class="db-2-main-com">
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db2.png')}}" alt="" />
                                <a href="{{route('packages.index')}}"><span>Packages</span></a>

                            </div>
                        </div>
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db3.png')}}" alt="" />
                                <a href="{{route('hotels.index')}}"><span>Hotels</span></a>

                            </div>
                        </div>
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db1.png')}}" alt="" />
                                <a href="{{route('airports.index')}}"><span>Airports</span></a>

                            </div>
                        </div>
                    </div>
                    <div class="db-2-main-com">
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db4.png')}}" alt="" />
                                <a href="{{route('countries.index')}}"><span>Countries</span></a>

                            </div>
                        </div>
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db5.png')}}" alt="" />
                                <a href="{{route('users.index')}}"><span>Users</span></a>

                            </div>
                        </div>
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db6.png')}}" alt="" />
                                <a href="{{route('pages.index')}}"><span>Pages</span></a>

                            </div>
                        </div>
                    </div>
                    <div class="db-2-main-com">
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db7.png')}}" alt="" />
                                <a href="{{route('home')}}"><span>Contact Mails</span></a>

                            </div>
                        </div>
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db8.png')}}" alt="" />
                                <a href="{{route('home')}}"><span>Expert Review</span></a>

                            </div>
                        </div>
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db9.png')}}" alt="" />
                                <a href="{{route('advertisments.index')}}"><span>Advertisements</span></a>

                            </div>
                        </div>
                    </div>
                    <div class="db-2-main-com">
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db10.png')}}" alt="" />
                                <a href="changepassword.html"><span>Change Password</span></a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <!--END DASHBOARD-->
@endsection

resources/views/leftbar.blade.php
<div class="db-l">

    <div class="db-l-2">
        @if(\Illuminate\Support\Facades\Auth::user()->user_level==1)
            <ul>
                <li>
                    <a href="{{route('dashboard')}}"> Dashboard </a>
                </li>
                <li>
                    <a href="{{route('orderD')}}"> Orders</a>
                </li>
            </ul>
        @elseif(\Illuminate\Support\Facades\Auth::user()->user_level==2)
            <ul>
                <li>
                    <a href="{{route('dashboard')}}"> Dashboard </a>
                </li>
                <li>
                    <a href="{{route('packages.index')}}"> Packages</a>
                </li>
            </ul>

        @elseif(\Illuminate\Support\Facades\Auth::user()->user_level==3)
            <ul>
                <li>
                    <a href="{{route('dashboard')}}"> Dashboard </a>
                </li>
                <li>
                    <a href="{{route('packages.index')}}"> Packages</a>
                </li>
                <li>
                    <a href="{{route('orderD')}}"> Orders</a>
                </li>
            </ul>
        @elseif(\Illuminate\Support\Facades\Auth::user()->user_level==4)
            <ul>
                <li>
                    <a href="{{route('home')}}"> Dashboard </a>
                </li>
                <li>
                    <a href="{{route('packages.index')}}"> Packages</a>
                </li>
                <li>
                    <a href="{{route('hotels.index')}}"> Hotels</a>
                </li>
                <li>
                    <a href="{{route('airports.index')}}">Airport</a>
                </li>
                <li>
                    <a href="{{route('countries.index')}}"> Countries</a>
                </li>
                <li>
                    <a href="{{route('users.index')}}">User</a>
                </li>
                <li>
                    <a href="{{route('pages.index')}}">Pages</a>
                </li>
                <li>
                    <a href="{{route('home')}}">Contact Mails</a>
                </li>
                <li>
                    <a href="{{route('home')}}">Expert Review</a>
                </li>
                <li>
                    <a href="{{route('advertisments.index')}}">Advertisement</a>
                </li>
            </ul>
        @else

        @endif
    </div>
</div>

resources/views/partnerdashboard.blade.php
@extends('master')
@section('content')
    <!--DASHBOARD-->
    <section>
        <div class="db">
            <!--LEFT SECTION-->
            @include('leftbar')
            <!--CENTER SECTION-->
            <div class="db-2">
                <div class="db-2-com db-2-main">

                    <div class="db-2-main-com">
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db2.png')}}" alt="" />
                                <a href="{{route('packages.index')}}"><span>Packages</span></a>

                            </div>
                        </div>
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db10.png')}}" alt="" />
                                <a href="{{route('changepassword')}}"><span>Change Password</span></a>

                            </div>
                        </div>
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/list.png')}}" alt="" />
                                <a href="{{route('orderD')}}"><span>Order Details</span></a>

                            </div>
                        </div>
                    </div>
                    <div class="db-2-main-com">
                        <div class="db-2-main-1">
                            <div class="db-2-main-2">
                                <a href="#"><span>Stats</span></a>

                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <p style="font-size:20px; color:#23527c; padding-left:7px"><b>User Who Buy</b></p>
                                    <p style="font-size:20px; padding-left:7px">5</p>
                                </div>
                                <div class="col-md-6">
                                    <p style="font-size:20px; color:#23527c; padding-left:5px"><b>User Who Contact</b></p>
                                    <p style="font-size:20px; padding-left:7px">4</p>
                                </div>
                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>
    </section>
    <!--END DASHBOARD-->
    @endsection

resources/views/regulardashboard.blade.php
@extends('master')
@section('content')
    <!--DASHBOARD-->
    <section>
        <div class="db">
            <!--LEFT SECTION-->
            @include('leftbar')
            <!--CENTER SECTION-->
            <div class="db-2">
                <div class="db-2-com db-2-main">

                    <div class="db-2-main-com">
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db2.png')}}" alt="" />
                                <a href="{{route('packages.index')}}"><span>Packages</span></a>

                            </div>
                        </div>
                        <div class="db-2-main-1">
                            <div class="db-2-main-2"> <img src="{{asset('images/icon/db10.png')}}" alt="" />
                                <a href="{{route('changepassword')}}"><span>Change Password</span></a>

                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </section>
    <!--END DASHBOARD-->
    @endsection

resources/views/userdashboard.blade.php
@extends('master')
@section('content')
<!--DASHBOARD-->
<section>
    <div class="db">
        <!--LEFT SECTION-->
        @include('leftbar')
        <!--CENTER SECTION-->
        <div class="db-2">
            <div class="db-2-com db-2-main">


                <div class="db-2-main-com">

                    <div class="db-2-main-1">
                        <div class="db-2-main-2"> <img src="{{asset('images/icon/db5.png')}}" alt="" />
                            <a href="{{route('orderD')}}"><span>Orders</span></a>

                        </div>
                    </div>
                    <div class="db-2-main-1">
                        <div class="db-2-main-2"> <img src="{{asset('images/icon/db10.png')}}" alt="" />
                            <a href="{{route('changepassword')}}"><span>Change Password</span></a>

                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</section>
<!--END DASHBOARD-->
    @endsection