routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@wellcome')->name('default');
//Route::get('/Dashboard','UserController@dashboard')->name('userDashboard');
Route::get('/Dashboard','HomeController@index')->name('dashboard');
Route::get('/order','OrderController@index')->name('orderD');
Route::get('/profile','UserController@userprofile')->name('profile');
Route::get('/changepassword','UserController@changepassword')->name('changepassword');
Route::post('/updateProfile/{id}','UserController@updateProfile')->name('Updateprofile');
Route::post('/updatePassword/{id}','UserController@updatePassword')->name('updatePassword');
Route::resource('users', 'UserController');
Route::resource('countries', 'CountryController');
Route::resource('hotels', 'HotelController');
Route::resource('photos', 'PhotoController');
Route::resource('airports', 'AirPortController');
Route::resource('advertisments', 'AdvertismentController');
Route::resource('pages', 'PageController');
Route::get('/getPackage/{id}', 'PageController@getPackage')->name('getPackage');
Route::resource('packages', 'PackageController');
Route::resource('orders', 'OrderController');
Route::get('ajax/user','UserController@ajax')->name('ajaxUser');
Route::get('ajax/country','CountryController@ajax')->name('ajaxCountry');
Route::get('ajax/hotel','HotelController@ajax')->name('ajaxHotel');
Route::get('ajax/airport','AirPortController@ajax')->name('ajaxAirport');
Route::get('ajax/advertisement','AdvertismentController@ajax')->name('ajaxAdvertisement');
Route::get('ajax/pages','PageController@ajax')->name('ajaxPage');
Route::get('ajax/package','PackageController@ajax')->name('ajaxPackage');
Route::get('ajax/order','OrderController@ajax')->name('orderAjax');
Auth::routes();
Route::get('/registeragency','PageController@agency')->name('regAgecny');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/activate/token={token}', 'ActivationController@activate')->name('activate');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
class User extends Authenticatable
{
    use Notifiable,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
     protected $fillable = ['fname', 'lname', 'email', 'password', 'address', 'city', 'state', 'zipcode', 'country_id', 'homephone','mobilephone','officephone','user_level'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function country(){
       return $this->belongsTo('App\Country');
    }
    public function orders(){
        return $this->hasMany('App\Order');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Country;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Facades\DataTables;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $user = Auth::user();
        if ($user->user_level == 4) {
            return view('users.index');
        } else {
            return redirect()->back();
        }
    }

    public function ajax()
    {
        $users = User::where('id', '>', 0);
        $users->with('country');
        return Datatables::of($users)
            ->addColumn('action', function (User $user) {
                $btn = '<a href=""><i class="fa fa-eye"></i></a>
	   	<a href="' . route("users.edit", $user->id) . '"><i class="fa fa-edit"></i></a>';
                return $btn . view(' users.delete', compact('user'))->render();
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $user = Auth::user();
        if ($user->user_level == 4) {
            $countries = Country::all();
            return view('users.add', compact('countries'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'fname' => ['required', 'string', 'max:255'],
            'lname' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'address' => ['required', 'string'],
            'city' => ['required', 'string','max:50'],
            'state' => ['required', 'string','max:50'],
            'zipcode' => ['required', 'string','max:20'],
            'country' => ['required', 'string'],
            'homenumber' => ['required', 'string','max:20'],
            'mobilenumber' => ['required', 'string','max:20'],
            'officephone' => ['string','max:20'],
            'user_level' => ['required', 'string','max:20']
        ]);
        $user = new User();
        $user->fname = $request->fname;
        $user->lname = $request->lname;
        $user->email = $request->email;
        $user->address = $request->address;
        $user->city = $request->city;
        $user->state = $request->state;
        $user->zipcode = $request->zipcode;
        $user->country_id = $request->country;
        $user->homephone = $request->homenumber;
        $user->mobilephone = $request->mobilenumber;
        $user->officephone = $request->officephone;
        $user->password = Hash::make($request->password);
        $user->user_level = $request->user_level;
        $user->save();
        return redirect(route('users.index'))->with('msg', 'User Created Successfuly');

    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return Response
     */
    public function edit(User $user)
    {
//        return $user;
        $auth = Auth::user();
        $countries=Country::all();
        if ($auth->user_level == 4) {
            return view('users.edit', compact('user','countries'));
        }else {
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param User $user
     * @return Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'fname' => ['required', 'string', 'max:255'],
            'lname' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'address' => ['required', 'string'],
            'city' => ['required', 'string','max:50'],
            'state' => ['required', 'string','max:50'],
            'zipcode' => ['required', 'string','max:20'],
            'country' => ['required', 'string'],
            'homenumber' => ['required', 'string','max:20'],
            'mobilenumber' => ['required', 'string','max:20'],
            'officephone' => ['string','max:20'],
            'user_level' => ['required', 'string','max:20']
        ]);
        $user->fname = $request->fname;
        $user->lname = $request->lname;
        $user->email = $request->email;
        $user->address = $request->address;
        $user->city = $request->city;
        $user->state = $request->state;
        $user->zipcode = $request->zipcode;
        $user->country_id = $request->country;
        $user->approved_status = $request->status_approved;
        $user->approved_by=Auth::id();
        $user->homephone = $request->homenumber;
        $user->mobilephone = $request->mobilenumber;
        $user->officephone = $request->officephone;
        $user->user_level = $request->user_level;
        $user->save();
        return redirect(route('users.index'))->with('msg', 'User Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect(route('users.index'))->with('msg', 'User deleted Successfuly');
    }

    public function dashboard()
    {
        $user = Auth::user();
        if ($user->user_level == 1) {
            return view('userdashboard', compact('user'));
        } else if ($user->user_level == 2) {
            return view('regulardashboard', compact('user'));
        } elseif ($user->user_level == 3) {
            return view('partnerdashboard', compact('user'));
        } elseif ($user->user_level == 4) {
            return view('home', compact('user'));
        } else {
            return view('userdashboard');
        }
    }
    public function userprofile(){
        $user=Auth::user();
        return view('users.profile',compact('user'));
    }
    public function changepassword(){
        $user=Auth::user();
        return view('changepass',compact('user'));
    }
    public function updatePassword(Request $request,User $user){
            $user=Auth::user();
            $user->password = Hash::make($request->password);
            $user->save();
        return redirect()->back();
    }
}

resources/views/users/add.blade.php
@extends('master')
@section('content')
    <!--DASHBOARD-->
    <section>
        <div class="db">
            <!--LEFT SECTION-->
        @include('leftbar')
        <!--CENTER SECTION-->
            <div class="db-2">

                <style type="text/css">
                    .tr-regi-form {
                        box-shadow: 0px 0px 0px rgba(0, 0, 0, 0) !important;
                    }
                </style>
                <div class="input-field col s2 pull-right">
                    <a href="{{route('users.create')}}">
                        <button>Add New</button>
                    </a>
                </div>
                <div class="tr-regi-form container" style="width:80%;margin: 20px;">

                    <h4>Add User</h4>
                    <form method="POST" action="{{ route('users.store') }}" class="col s12">
                        @csrf

                        <div class="row">
                            <div class="input-field col m6 s12">
                                <input class="validate @error('fname') is-invalid @enderror" id="fname" type="text"
                                       name="fname" value="{{ old('fname') }}" required autocomplete="fname">
                                <label>First Name</label>
                                @error('fname')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="input-field col m6 s12">
                                <input type="text" class="validate @error('lname') is-invalid @enderror" id="lname"
                                       type="text" name="lname" value="{{ old('lname') }}" required
                                       autocomplete="lname">
                                <label>Last Name</label>
                                @error('lname')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-field col m4 s12">
                                <input type="email" class="validate @error('email') is-invalid @enderror" id="email"
                                       name="email" value="{{ old('email') }}" required autocomplete="email">
                                <label>Email</label>
                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="input-field col m4 s12">
                                <input type="password" id="password" name="password"
                                       class="validate @error('password') is-invalid @enderror"
                                       value="{{ old('password') }}" required>
                                <label>Password</label>
                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="input-field col m4 s12">
                                <label>Confirm Password</label>
                                <input id="password-confirm" type="password"
                                       class="validate @error('password') is-invalid @enderror"
                                       name="password_confirmation" required autocomplete="new-password">

                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input type="text" class="validate @error('password') is-invalid @enderror"
                                       name="address" id="address" value="{{old('address')}}">
                                <label>Address</label>
                                @error('address')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col m4 s12">
                                <input type="text" class="validate @error('city') is-invalid @enderror" name="city"
                                       id="city" value="{{old('city')}}">
                                <label>City</label>
                                @error('city')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="input-field col m4 s12">
                                <input type="text" class="validate @error('state') is-invalid @enderror" name="state"
                                       id="state" value="{{old('state')}}">
                                <label>State</label>
                                @error('state')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="input-field col m4 s12">
                                <input type="text" class="validate @error('zipcode') is-invalid @enderror"
                                       name="zipcode" id="zipcode" value="{{old('zipcode')}}">
                                <label>Zip</label>
                                @error('zipcode')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="row">
                                <div class="input-field col m6 s12">
                                    <select name="country" class="validate @error('country') is-invalid @enderror">
                                        <option value="" disabled selected>Select Country</option>
                                        @foreach($countries as $country)
                                            <option value="{{$country->id}}">{{$country->name}}</option>
                                        @endforeach
                                    </select>
                                    @error('country')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="input-field col m6 s12 GeneralUser">
                                    <input type="number" id="homenumber" value="{{old('homenumber')}}" name="homenumber"
                                           class="validate  @error('homenumber') is-invalid @enderror">
                                    <label>Home Phone</label>
                                    @error('homenumber')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col m4 s12">
                                    <select class="roles" name="user_level">
                                        <option value="1">User</option>
                                        <option value="2">Regular Agency</option>
                                        <option value="3">Partner Agency</option>
                                        <option value="4">Admin</option>
                                    </select>
                                </div>

                            <div class="input-field col m4 s12 AgencyUser">
                                <input type="number" id="officenumber" value="{{old('officenumber')}}"
                                       name="officenumber"
                                       class="validate  @error('officenumber') is-invalid @enderror">
                                <label>Office Phone</label>
                                @error('officenumber')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                                <div class="input-field col m4 s12 AgencyUser">
                                <input type="number" id="mobilenumber" value="{{old('mobilenumber')}}"
                                       name="mobilenumber"
                                       class="validate  @error('mobilenumber') is-invalid @enderror">
                                <label>Mobile Phone</label>
                                @error('mobilenumber')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                      </div>

                        <div class="row">
                            <div class="input-field col s12">
                                <input type="submit" value="submit" class="waves-effect waves-light btn-large full-btn">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    @section('script')

        @endsection
@endsection

resources/views/users/delete.blade.php
<a href="#" onclick="frmdlt{{$user->id}}.submit();"  title="Delete"><i class="fa fa-trash"></i> </a>
<form name="frmdlt{{$user->id}}" action="{{ route('users.destroy', $user->id)}}" method="post">
    {!! method_field('delete') !!}
    {{csrf_field()}}
</form>

resources/views/users/index.blade.php
@extends('master')
@section('content')
    <!--DASHBOARD-->
    <section>
        <div class="db">
            <!--LEFT SECTION-->
        @include('leftbar')
        <!--CENTER SECTION-->
            <div class="db-2" style="padding: 30px;">
                @if(session()->has('msg'))
                    <div class="alert alert-success">
                        {{ session()->get('msg') }}
                    </div>
                @endif
                <h4 style="text-align:center">Users</h4>
                <div style="float:right;">
                    <a href="{{route('users.create')}}" class="btn btn-primary">Add User</a>
                </div>
                <br><br>

                <div style="overflow-x:auto;">
                    <table class="table table-bordered table-responsive" id="data-table">
                        <tr>
                            <th>Id</th>
                            {{--      <th>Role</th>--}}
                            <th>Country</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Address</th>
                            <th>Email</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Zip</th>
                            <!-- <th>Url</th> -->
                            <th>Actions</th>
                        </tr>
                        {{--    @foreach($users as $user)--}}
                        {{--    <tr>--}}

                        {{--      <td>{{$user->id}}</td>--}}
                        {{--      <td><a href="#">USER</a></td>--}}
                        {{--      <td><a href="#">{{$user->country_id}}</a></td>--}}
                        {{--      <td>{{$user->fname}}</td>--}}
                        {{--      <td>{{$user->lname}}</td>--}}
                        {{--      <!-- <td></td> -->--}}
                        {{--      <td>{{$user->email}}</td>--}}
                        {{--      <td>{{$user->city}}</td>--}}
                        {{--      <td>{{$user->state}}</td>--}}
                        {{--      <td>{{$user->zipcode}}</td>--}}
                        {{--      <!-- <td>www.dareleiman.com</td> -->--}}
                        {{--	<td>--}}
                        {{--	   	<a href=""><i class="fa fa-eye"></i></a>--}}
                        {{--	   	<a href="{{route('users.edit',$user->id)}}"><i class="fa fa-edit"></i></a>--}}
                        {{--	    <a href="{{route('users.destroy',$user->id)}}"><i class="fa fa-trash-o"></i></a>--}}
                        {{--	</td>--}}
                        {{--    </tr>--}}
                        {{--    @endforeach--}}
                    </table>
                </div>


            </div>

        </div>
    </section>
    <!--END DASHBOARD-->
 @section('script')
    <script>
        $(function () {

            var table = $('#data-table').DataTable({
                dom: 'Bfrtip',
                processing: true,
                serverSide: true,
                ajax: "{{ route('ajaxUser') }}",
                buttons: [
                    {{--{--}}
                        {{--    text: 'Add User',--}}
                        {{--    action: '{{route('users.create')}}',--}}
                        {{--    className:'btn btn-primary'--}}
                        {{--},--}}
                        'copy', 'excel', 'pdf'
                ],
                columns: [
                    {data: 'id', name: 'id', title: 'id'},
                    {data: 'country.name', name: 'name', title: 'Country'},
                    {data: 'fname', name: 'fname', title: 'First Name'},
                    {data: 'lname', name: 'lname', title: 'Last Name'},
                    {data: 'email', name: 'email', title: 'Email'},
                    {data: 'address', name: 'address', title: 'Address'},
                    {data: 'city', name: 'city', title: 'City'},
                    {data: 'state', name: 'state', title: 'State'},
                    {data: 'zipcode', name: 'zipcode', title: 'ZipCode'},
                    {data: 'action', name: 'action', title: 'Action', orderable: false, searchable: false},
                ]
            });

        });
    </script>
 @endsection
@stop