routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@wellcome')->name('default');
//Route::get('/Dashboard','UserController@dashboard')->name('userDashboard');
Route::get('/Dashboard','HomeController@index')->name('dashboard');
Route::get('/order','OrderController@index')->name('orderD');
Route::get('/profile','UserController@userprofile')->name('profile');
Route::get('/changepassword','UserController@changepassword')->name('changepassword');
Route::post('/updateProfile/{id}','UserController@updateProfile')->name('Updateprofile');
Route::post('/updatePassword/{id}','UserController@updatePassword')->name('updatePassword');
Route::resource('users', 'UserController');
Route::resource('countries', 'CountryController');
Route::resource('hotels', 'HotelController');
Route::resource('photos', 'PhotoController');
Route::resource('airports', 'AirPortController');
Route::resource('advertisments', 'AdvertismentController');
Route::resource('pages', 'PageController');
Route::get('/getPackage/{id}', 'PageController@getPackage')->name('getPackage');
Route::resource('packages', 'PackageController');
Route::resource('orders', 'OrderController');
Route::get('ajax/user','UserController@ajax')->name('ajaxUser');
Route::get('ajax/country','CountryController@ajax')->name('ajaxCountry');
Route::get('ajax/hotel','HotelController@ajax')->name('ajaxHotel');
Route::get('ajax/airport','AirPortController@ajax')->name('ajaxAirport');
Route::get('ajax/advertisement','AdvertismentController@ajax')->name('ajaxAdvertisement');
Route::get('ajax/pages','PageController@ajax')->name('ajaxPage');
Route::get('ajax/package','PackageController@ajax')->name('ajaxPackage');
Route::get('ajax/order','OrderController@ajax')->name('orderAjax');
Auth::routes();
Route::get('/registeragency','PageController@agency')->name('regAgecny');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/activate/token={token}', 'ActivationController@activate')->name('activate');

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    public function users(){
        return $this->hasMany('App\User');
    }
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;
use App\Country;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $user = Auth::user();
        if($user->user_level==4) {
            return view('countries.index');
        }else{
            return redirect()->back();
        }
    }
    public function ajax(){
        $countries=Country::where('id','>',0);
        return Datatables::of($countries)
            ->addColumn('action', function(Country $country){
                $btn = '<a href=""><i class="fa fa-eye"></i></a>
	   	<a href="'.route("countries.edit", $country->id).'"><i class="fa fa-edit"></i></a>';

                return $btn.view(' countries.delete', compact('country'))->render();
            })
            ->rawColumns(['action'])
            ->make(true);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        if($user->user_level==4) {
        return view('countries.create');
        }else{
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'iso' => ['required', 'string', 'max:50'],
            'iso_3' => ['required', 'string', 'max:50'],
            'name' => ['required', 'string', 'max:50'],
            'nice_name' => ['required', 'string', 'max:50'],
            'numcode' => ['required', 'string','max:50'],
            'phonecode' => ['required', 'string','max:50'],
        ]);
        $country = new Country();
        $country->iso = $request->iso;
        $country->iso_3 = $request->iso_3;
        $country->name = $request->name;
        $country->nice_name = $request->nice_name;
        $country->numcode = $request->numcode;
        $country->phonecode = $request->phonecode;
        $country->save();
        return redirect(route('countries.index'))->with('msg', 'Country created Successfuly');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function show(Country $country)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function edit(Country $country)
    {
        $user = Auth::user();
        if($user->user_level==4) {
            return view('countries.edit', compact('country'));
        }else{
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Country $country)
    {
        $request->validate([
            'iso' => ['required', 'string', 'max:50'],
            'iso_3' => ['required', 'string', 'max:50'],
            'name' => ['required', 'string', 'max:50'],
            'nice_name' => ['required', 'string', 'max:50'],
            'numcode' => ['required', 'string','max:50'],
            'phonecode' => ['required', 'string','max:50'],
        ]);
        $country->iso = $request->iso;
        $country->iso_3 = $request->iso_3;
        $country->name = $request->name;
        $country->nice_name = $request->nice_name;
        $country->numcode = $request->numcode;
        $country->phonecode = $request->phonecode;
        $country->save();
        return redirect(route('countries.index'))->with('msg', 'Country Updated Successfuly');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function destroy(Country $country)
    {
        $country->delete();
        return redirect(route('countries.index'))->with('msg', 'Country deleted Successfuly');

    }
}

resources/views/countries/create.blade.php
 @extends('master')
@section('content')
    <!--DASHBOARD-->
    <section>
        <div class="db">
            <!--LEFT SECTION-->
        @include('leftbar')
        <!--CENTER SECTION-->
			<div class="db-2">
				<div class="tr-regi-form" style="width:80%;">
				<h4>Add Country</h4>
				@if(session()->has('msg'))
			    <div class="alert alert-success">
			        {{ session()->get('msg') }}
    			</div>
				@endif
				<form action="{{route('countries.store')}}" class="col s12" method="post">
					@csrf
					<div class="row">
						<div class="input-field col m4 s12">
						<h5 style="text-align:left">Iso</h5>
							<input type="text" name="iso" class="validate @error('iso') is-invalid @enderror"
							value="{{ old('iso') }}">
							  @error('iso')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
						<div class="input-field col m4 s12">
						<h5 style="text-align:left">Name</h5>
							<input type="text" name="name" class="validate @error('name') is-invalid @enderror"
							value="{{ old('name') }}">
							  @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
						<div class="input-field col m4 s12">
						<h5 style="text-align:left">Nice Name</h5>
							<input type="text" name="nice_name" class="validate @error('nice_name') is-invalid @enderror"
							value="{{ old('nice_name') }}">
							  @error('nice_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
					</div>
					
				
					<div class="row">
						<div class="input-field col m4 s12">
						<h5 style="text-align:left">Iso 3</h5>
							<input type="text" name="iso_3" class="validate @error('iso_3') is-invalid @enderror" value="{{ old('iso_3') }}">
							  @error('iso_3')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
							<div class="input-field col m4 s12">
						<h5 style="text-align:left">Numcode</h5>
							<input type="number" name="numcode" class="validate @error('numcode') is-invalid @enderror" value="{{ old('numcode') }}">
							  @error('numcode')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
						<div class="input-field col m4 s12">
						<h5 style="text-align:left">Phonecode</h5>
							<input type="number" name="phonecode" class="validate @error('phonecode') is-invalid @enderror" value="{{ old('phonecode') }}">
							  @error('phonecode')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
						
					</div>
					
					
					
					<div class="row">
						<div class="input-field col s12">
							<input type="submit" value="Save" class="waves-effect waves-light btn-large full-btn"> </div>
					</div>
				</form>
				
			</div>
			</div>

		</div>
	</section>
	<!--END DASHBOARD-->
@endsection

resources/views/countries/delete.blade.php
<a href="#" onclick="frmdlt{{$country->id}}.submit();"  title="Delete"><i class="fa fa-trash"></i> </a>
<form name="frmdlt{{$country->id}}" action="{{ route('countries.destroy', $country->id)}}" method="post">
    {!! method_field('delete') !!}
    {{csrf_field()}}
</form>

resources/views/countries/edit.blade.php
@extends('master')
@section('content')
    <!--DASHBOARD-->
    <section>
        <div class="db">
            <!--LEFT SECTION-->
        @include('leftbar')
        <!--CENTER SECTION-->
			<div class="db-2">
				<div class="tr-regi-form" style="width:80%;">
				<h4>Edit Country</h4>
				@if(session()->has('msg'))
			    <div class="alert alert-success">
			        {{ session()->get('msg') }}
    			</div>
				@endif
				<form action="{{route('countries.update',$country->id)}}" class="col s12" method="post">
					@csrf
                    {{method_field('PATCH')}}
					<div class="row">
						<div class="input-field col m4 s12">
						<h5 style="text-align:left">Iso</h5>
							<input type="text" name="iso" class="validate @error('iso') is-invalid @enderror"
							value="{{ old('iso',$country->iso) }}">
							  @error('iso')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
						<div class="input-field col m4 s12">
						<h5 style="text-align:left">Name</h5>
							<input type="text" name="name" class="validate @error('name') is-invalid @enderror"
							value="{{ old('name',$country->name) }}">
							  @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
						<div class="input-field col m4 s12">
						<h5 style="text-align:left">Nice Name</h5>
							<input type="text" name="nice_name" class="validate @error('nice_name') is-invalid @enderror"
							value="{{ old('nice_name',$country->nice_name) }}">
							  @error('nice_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
					</div>


					<div class="row">
						<div class="input-field col m4 s12">
						<h5 style="text-align:left">Iso 3</h5>
							<input type="text" name="iso_3" class="validate @error('iso_3') is-invalid @enderror" value="{{ old('iso_3',$country->iso_3) }}">
							  @error('iso_3')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
							<div class="input-field col m4 s12">
						<h5 style="text-align:left">Numcode</h5>
							<input type="number" name="numcode" class="validate @error('numcode') is-invalid @enderror" value="{{ old('numcode',$country->numcode) }}">
							  @error('numcode')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>
						<div class="input-field col m4 s12">
						<h5 style="text-align:left">Phonecode</h5>
							<input type="number" name="phonecode" class="validate @error('phonecode') is-invalid @enderror" value="{{ old('phonecode',$country->phonecode) }}">
							  @error('phonecode')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
						</div>

					</div>



					<div class="row">
						<div class="input-field col s12">
							<input type="submit" value="Save" class="waves-effect waves-light btn-large full-btn"> </div>
					</div>
				</form>

			</div>
			</div>

		</div>
	</section>
	<!--END DASHBOARD-->
@endsection

resources/views/countries/index.blade.php
 @extends('master')
@section('content')
<style>
table {
  margin:10px;
  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  border: 1px solid #ddd;
}

th, td {
  text-align: center;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}
</style>
     <!--DASHBOARD-->
     <section>
         <div class="db">
             <!--LEFT SECTION-->
         @include('leftbar')
         <!--CENTER SECTION-->
			<div class="db-2" style="padding: 30px;">
                @if(session()->has('msg'))
                    <div class="alert alert-success">
                        {{ session()->get('msg') }}
                    </div>
                @endif
				<h4 style="text-align:center">Countries</h4>
                <div style="float:right;">
                    <a href="{{route('countries.create')}}" class="btn btn-primary">Add Country</a>
                </div><br><br>
				<div >
  <table class="table table-bordered" id="data-table">
    <tr>
      <th>Id</th>
      <th>Iso</th>
      <th>Name</th>
      <th>Nicename</th>
{{--	  <th>Iso3</th>--}}
	  <th>Numcode</th>
	  <th>Phonecode</th>
	  <th>Created</th>
	  <th>Modified</th>
	  <th>Actions</th>
    </tr>
{{--    @foreach($countries as $country)--}}
{{--    <tr>--}}
{{--      <td>{{$country->id}}</td>--}}
{{--      <td>{{$country->iso}}</td>--}}
{{--      <td>{{$country->name}}</td>--}}
{{--      <td>{{$country->nice_name}}</td>--}}
{{--	  <td>{{$country->iso_3}}</td>--}}
{{--	  <td>{{$country->numcode}}</td>--}}
{{--	  <td>{{$country->phonecode}}</td>--}}
{{--	  <td>{{$country->created_at}}</td>--}}
{{--	  <td>{{$country->updated_at}}</td>--}}
{{--	   <td><i class="fa fa-eye"></i>--}}
{{--	   <i class="fa fa-edit"></i>--}}
{{--	   <i class="fa fa-trash-o"></i>--}}
{{--	   <i class="fa fa-clone"></i></td>--}}
{{--    </tr>--}}
{{--    @endforeach--}}
  </table>
</div>


			</div>

		</div>
	</section>
	<!--END DASHBOARD-->
 @section('script')
     <script>
         $(function () {

             var table = $('#data-table').DataTable({
                 dom: 'Bfrtip',
                 processing: true,
                 serverSide: true,
                 ajax: "{{ route('ajaxCountry') }}",
                 buttons: [
                     {{--{--}}
                         {{--    text: 'Add Advertisements',--}}
                         {{--    action: '{{route('advertisments.create')}}',--}}
                         {{--    className:'btn btn-primary'--}}
                         {{--},--}}
                         'copy', 'excel', 'pdf'
                 ],
                 columns: [
                     {data: 'id', name: 'id',title:'Id'},
                     {data: 'iso', name: 'iso',title:'Iso'},
                     {data: 'name', name: 'name',title:'Name'},
                     {data: 'nice_name', name: 'nice_name',title:'Nicename'},
                     // {data: 'iso_3', name: 'iso_3',title:'Iso3'},
                     {data: 'numcode', name: 'numcode',title:'Numcode'},
                     {data: 'phonecode', name: 'phonecode',title:'Phonecode'},
                     {data: 'created_at', name: 'created_at',title:'Created'},
                     {data: 'updated_at', name: 'updated_at',title:'Modified'},
                     {data: 'action', name: 'action',title:'Action', orderable: false, searchable: false},
                 ]
             });

         });
     </script>
 @endsection
	@endsection