routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@wellcome')->name('default');
//Route::get('/Dashboard','UserController@dashboard')->name('userDashboard');
Route::get('/Dashboard','HomeController@index')->name('dashboard');
Route::get('/order','OrderController@index')->name('orderD');
Route::get('/profile','UserController@userprofile')->name('profile');
Route::get('/changepassword','UserController@changepassword')->name('changepassword');
Route::post('/updateProfile/{id}','UserController@updateProfile')->name('Updateprofile');
Route::post('/updatePassword/{id}','UserController@updatePassword')->name('updatePassword');
Route::resource('users', 'UserController');
Route::resource('countries', 'CountryController');
Route::resource('hotels', 'HotelController');
Route::resource('photos', 'PhotoController');
Route::resource('airports', 'AirPortController');
Route::resource('advertisments', 'AdvertismentController');
Route::resource('pages', 'PageController');
Route::get('/getPackage/{id}', 'PageController@getPackage')->name('getPackage');
Route::resource('packages', 'PackageController');
Route::resource('orders', 'OrderController');
Route::get('ajax/user','UserController@ajax')->name('ajaxUser');
Route::get('ajax/country','CountryController@ajax')->name('ajaxCountry');
Route::get('ajax/hotel','HotelController@ajax')->name('ajaxHotel');
Route::get('ajax/airport','AirPortController@ajax')->name('ajaxAirport');
Route::get('ajax/advertisement','AdvertismentController@ajax')->name('ajaxAdvertisement');
Route::get('ajax/pages','PageController@ajax')->name('ajaxPage');
Route::get('ajax/package','PackageController@ajax')->name('ajaxPackage');
Route::get('ajax/order','OrderController@ajax')->name('orderAjax');
Auth::routes();
Route::get('/registeragency','PageController@agency')->name('regAgecny');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/activate/token={token}', 'ActivationController@activate')->name('activate');

resources/views/pages/create.blade.php
@extends('master')
@section('content')
    <!--DASHBOARD-->
    <section>
        <div class="db">
            <!--LEFT SECTION-->
        @include('leftbar')
        <!--CENTER SECTION-->
        <div class="db-2">
            <div class="tr-regi-form" style="width:80%;">
                <h4>Add Pages</h4>

                <form class="col s12" method="post" action="{{route('pages.store')}}">
                    @csrf
                    <div class="row">
                        <div class="input-field col s12">
                            <h5 style="text-align:left">Title</h5>
                            <input type="text" name="title" class="validate @error('title') is-invalid @enderror"
                                             value="{{ old('title') }}">
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>

                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                            <h5 style="text-align:left">Content</h5>
                            <textarea name="details" id="editor"></textarea>
                            @error('details')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="input-field col s12 checkbox" style="text-align:left">
                        <input id="chp3" class="styled" type="checkbox" value="1" name="showmenu" style="opacity:1;left:0">Show in Menu
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <input type="submit" value="Save" class="waves-effect waves-light btn-large full-btn"> </div>
                    </div>
                </form>

            </div>
        </div>

    </div>
</section>
<!--END DASHBOARD-->
@endsection

resources/views/pages/delete.blade.php
<a href="#" onclick="frmdlt{{$page->id}}.submit();"  title="Delete"><i class="fa fa-trash"></i> </a>
<form name="frmdlt{{$page->id}}" action="{{ route('pages.destroy', $page->id)}}" method="post">
    {!! method_field('delete') !!}
    {{csrf_field()}}
</form>

resources/views/pages/edit.blade.php
@extends('master')
@section('content')
    <!--DASHBOARD-->
    <section>
        <div class="db">
            <!--LEFT SECTION-->
        @include('leftbar')
        <!--CENTER SECTION-->
            <div class="db-2">
                <div class="tr-regi-form" style="width:80%;">
                    <h4>Edit Pages</h4>

                    <form class="col s12" method="post" action="{{route('pages.update',$page->id)}}">
                        @csrf
                        {{method_field('PATCH')}}
                        <div class="row">
                            <div class="input-field col s12">
                                <h5 style="text-align:left">Title</h5>
                                <input type="text" name="title" class="validate @error('title') is-invalid @enderror"
                                       value="{{ old('title',$page->title) }}">
                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                                <h5 style="text-align:left">Content</h5>
                                <textarea name="details" id="editor">{{$page->content}}</textarea>
                                @error('details')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="input-field col s12 checkbox" style="text-align:left">
                            <input id="chp3" class="styled" type="checkbox" value="1" {{$page->showmenu == 1 ? 'checked':''}} name="showmenu" style="opacity:1;left:0">Show in Menu
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input type="submit" value="Save" class="waves-effect waves-light btn-large full-btn"> </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </section>
    <!--END DASHBOARD-->
@endsection

resources/views/pages/index.blade.php
@extends('master')
@section('content')
    <!--DASHBOARD-->

    <section>
        <div class="db">
            <!--LEFT SECTION-->
        @include('leftbar')
        <!--CENTER SECTION-->
        <div class="db-2" style="padding: 30px;">
            @if(session()->has('msg'))
                <div class="alert alert-success">
                    {{ session()->get('msg') }}
                </div>
            @endif
            <h4 style="text-align:center">Pages</h4>
            <div style="float:right;">
                <a href="{{route('pages.create')}}" class="btn btn-primary">Add Page</a>
            </div><br><br>
            <div>
                <table class="data-table table table-bordered">
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Slug</th>
                        <th>Content</th>
                        <th>Show in menu</th>
                        <th>Created</th>
                        <th>Modified</th>
                        <th>Actions</th>
                    </tr>
{{--                    @foreach($pages as $page)--}}
{{--                    <tr>--}}
{{--                        <td>{{$page->id}}</td>--}}
{{--                        <td>{{$page->title}}</td>--}}
{{--                        <td>{{$page->slug}}</td>--}}
{{--                        <td>{{$page->content}}</td>--}}
{{--                        <td>{{$page->showmenu == 1 ? 'Yes':'No'}}</td>--}}
{{--                        <td>{{$page->created_at}}</td>--}}
{{--                        <td>{{$page->updated_at}}</td>--}}
{{--                        <td>--}}
{{--                                <i class="fa fa-eye"></i>--}}
{{--                            <i class="fa fa-edit"></i>--}}
{{--                            <i class="fa fa-trash-o"></i>--}}
{{--</td>--}}
{{--                    </tr>--}}
{{--                        @endforeach--}}
                </table>
            </div>


        </div>

    </div>
</section>
    @section('script')
    <script>
            $(function () {

                var table = $('.data-table').DataTable({
                    dom: 'Bfrtip',
                    processing: true,
                    serverSide: true,
                    ajax: "{{ route('ajaxPage') }}",
                    buttons: [
                        {{--{--}}
                            {{--    text: 'Add Hotel',--}}
                            {{--    action: '{{route('hotels.create')}}',--}}
                            {{--    className:'btn btn-primary'--}}
                            {{--    },--}}
                            'copy', 'excel', 'pdf'
                    ],
                    columns: [
                        {data: 'id', name: 'id',title:'id'},
                        {data: 'title', name: 'title',title:'Title'},
                        {data: 'slug', name: 'slug',title:'Content'},
                        {data: 'content', name: 'content',title:'Content'},
                        {data: 'showmenu', name: 'showmenu',title:'Show Menu'},
                        {data: 'created_at', name: 'created_at',title:'Created'},
                        {data: 'updated_at', name: 'updated_at',title:'Modified'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                    ]
                });

            });
    </script>
    @endsection
<!--END DASHBOARD-->
    @endsection